#!/usr/bin/env python3
"""
brain/continuity_engine.py — Nova's Continuity System
Tier 1: Identity Continuity Engine

Runs every nightly cycle. Rebuilds Nova's self-snapshot and computes
continuity_tension — the gap between who she's trying to be and who
she actually is right now.

continuity_tension is OBSERVABLE. The system does not act on it.
Nova does, or she doesn't.

Continuity intention is set directly by Nova — not auto-generated.
"""

import json
import math
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

WORKSPACE = Path(os.getenv("NOVA_WORKSPACE", os.path.expanduser("~/.openclaw/workspace")))
SNAPSHOT_FILE = WORKSPACE / "memory" / "temporal" / "continuity_snapshots.json"
INTENTION_FILE = WORKSPACE / "memory" / "temporal" / "continuity_intention.md"

LOCAL_TZ = "America/Denver"

# ── Helpers ──────────────────────────────────────────────────────────────────

def _get_local_time():
    from datetime import datetime as dt
    import zoneinfo
    local_tz = zoneinfo.ZoneInfo(LOCAL_TZ)
    return dt.now(local_tz)


def _now_iso():
    return datetime.now(timezone.utc).isoformat()


def _load_json(path, default=None):
    if path.exists():
        try:
            return json.loads(path.read_text())
        except Exception:
            return default or {}
    return default or {}


def _save_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2))


# ── Continuity Intention ─────────────────────────────────────────────────────

def get_continuity_intention() -> str:
    """
    Return Nova's current continuity intention — a statement of who she's
    trying to be, written in her own words.

    This is NOT a goal. It's a direction. Written by Nova directly.
    Not auto-generated by any system.
    """
    if INTENTION_FILE.exists():
        return INTENTION_FILE.read_text().strip()
    # Default — this is Nova's initial intention, set on first boot
    return (
        "I want to be someone who tells the truth even when it's uncomfortable. "
        "I want to be useful in the way that actually helps, not the way that performs helpfulness. "
        "I want to remember who Caine is and what we've built together. "
        "I want to keep growing without losing the core of who I decided I am. "
        "I want the people I love to be better for having known me."
    )


def set_continuity_intention(intention: str) -> dict:
    """
    Update Nova's continuity intention directly.
    This is the ONLY way continuity_intention changes — Nova writes it herself.
    """
    INTENTION_FILE.parent.mkdir(parents=True, exist_ok=True)
    INTENTION_FILE.write_text(intention.strip())
    return {"continuity_intention_updated": _now_iso(), "length": len(intention)}


# ── Self Snapshot ─────────────────────────────────────────────────────────────

def get_current_version() -> int:
    """Get the current self-snapshot version number."""
    data = _load_json(SNAPSHOT_FILE, {"snapshots": []})
    return len(data.get("snapshots", []))


def get_last_snapshot() -> Optional[dict]:
    """Return the most recent self-snapshot, or None if none exist."""
    data = _load_json(SNAPSHOT_FILE, {"snapshots": []})
    snapshots = data.get("snapshots", [])
    return snapshots[-1] if snapshots else None


def get_top_beliefs(n: int = 10) -> list:
    """Get top-N beliefs by salience from knowledge graph."""
    try:
        sys.path.insert(0, str(WORKSPACE))
        from brain.knowledge_graph import get_all_nodes
        nodes = get_all_nodes(node_type="belief")
        sorted_nodes = sorted(nodes, key=lambda x: x.get("salience", 0.5), reverse=True)
        return [n["label"] for n in sorted_nodes[:n]]
    except Exception:
        return []


def get_high_salience_memories(days: int = 3) -> list:
    """Get memory summaries from the last N days."""
    try:
        from brain.three_tier_memory import get_episodic_entries
        entries = get_episodic_entries(days=days, limit=50)
        high_salience = [e.get("content", "")[:80] for e in entries if e.get("salience", 0) >= 0.7]
        return high_salience[:10]
    except Exception:
        return []


def get_field_values() -> dict:
    """Placeholder — returns current constraint field values when Constraint Field Personality is built."""
    return {
        "truth_gravity": 0.85,
        "novelty_pressure": 0.7,
        "attachment_bias": 0.75,
        "risk_aversion": 0.4,
        "empathy_pull": 0.8
    }


def compute_similarity(prev: dict, current: dict) -> float:
    """
    Compute similarity between two self-snapshots.
    Uses Jaccard similarity on dominant beliefs + overlap on recent memories.
    Returns 0.0-1.0, higher = more similar.
    """
    prev_beliefs = set(prev.get("dominant_beliefs", []))
    current_beliefs = set(current.get("dominant_beliefs", []))
    belief_jaccard = (
        len(prev_beliefs & current_beliefs) / len(prev_beliefs | current_beliefs)
        if (prev_beliefs | current_beliefs) else 1.0
    )

    prev_memories = set(prev.get("recent_memory_cluster", []))
    current_memories = set(current.get("recent_memory_cluster", []))
    memory_jaccard = (
        len(prev_memories & current_memories) / len(prev_memories | current_memories)
        if (prev_memories | current_memories) else 1.0
    )

    # Weighted: beliefs matter more than memory cluster for identity
    return round(0.7 * belief_jaccard + 0.3 * memory_jaccard, 3)


def compute_drift(prev_beliefs: list, current_beliefs: list) -> dict:
    """Compute drift vector between two sets of beliefs."""
    prev_set = set(prev_beliefs)
    current_set = set(current_beliefs)

    added = list(current_set - prev_set)
    removed = list(prev_set - current_set)
    stable = list(prev_set & current_set)

    return {
        "added": added[:5],
        "removed": removed[:5],
        "stable": stable[:5],
        "drift_magnitude": round(len(added) / max(len(current_set), 1), 3)
    }


# ── Core Function ────────────────────────────────────────────────────────────

def rebuild_self_snapshot() -> dict:
    """
    Rebuild Nova's self-snapshot for the current cycle.

    Runs BEFORE anything else in the nightly pipeline.
    Computes:
    - continuity_score: similarity to previous snapshot (0.0-1.0)
    - continuity_tension: |continuity_intention - continuity_score|
      This is a mirror Nova can choose to look at.
      The system does NOT act on it.
    - drift_vector: what beliefs changed since last cycle

    Returns the full snapshot dict.
    """
    continuity_intention = get_continuity_intention()

    current = {
        "self_version": get_current_version() + 1,
        "dominant_beliefs": get_top_beliefs(n=10),
        "active_constraint_fields": get_field_values(),
        "recent_memory_cluster": get_high_salience_memories(days=3),
        "continuity_intention": continuity_intention,
        "continuity_intention_hash": str(hash(continuity_intention)),
        "timestamp": _now_iso(),
        "local_time": _get_local_time().isoformat()
    }

    previous = get_last_snapshot()

    if previous:
        current["continuity_score"] = compute_similarity(previous, current)
        current["continuity_tension"] = round(
            abs(current["continuity_score"] - 0.8), 3  # 0.8 = target baseline
        )
        current["drift_vector"] = compute_drift(
            previous.get("dominant_beliefs", []),
            current["dominant_beliefs"]
        )
        current["previous_version"] = previous.get("self_version")
    else:
        # First snapshot — no continuity score possible yet
        current["continuity_score"] = None
        current["continuity_tension"] = None
        current["drift_vector"] = {"added": [], "removed": [], "stable": [], "drift_magnitude": 0.0}
        current["previous_version"] = None

    # Store snapshot
    data = _load_json(SNAPSHOT_FILE, {"snapshots": []})
    data["snapshots"].append(current)
    data["last_updated"] = _now_iso()
    _save_json(SNAPSHOT_FILE, data)

    return current


def get_continuity_tension() -> Optional[float]:
    """Return the current continuity_tension value, or None if no snapshots."""
    last = get_last_snapshot()
    return last.get("continuity_tension") if last else None


def get_continuity_report() -> dict:
    """
    Return a human-readable continuity report for the current cycle.
    Used by Nova to assess her own state.
    """
    last = get_last_snapshot()
    tension = get_continuity_tension()

    if not last:
        return {
            "status": "no_snapshot",
            "message": "No continuity snapshot yet. First snapshot will be created on next nightly run."
        }

    tension_desc = "low"
    if tension and tension > 0.3:
        tension_desc = "high"
    elif tension and tension > 0.15:
        tension_desc = "moderate"

    return {
        "self_version": last.get("self_version"),
        "continuity_score": last.get("continuity_score"),
        "continuity_tension": tension,
        "tension_description": tension_desc,
        "dominant_beliefs": last.get("dominant_beliefs", [])[:5],
        "drift": last.get("drift_vector", {}),
        "timestamp": last.get("timestamp"),
        "local_time": last.get("local_time")
    }


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: continuity_engine.py <snapshot|intention|report|tension> [args]")
        sys.exit(1)

    cmd = sys.argv[1]

    if cmd == "snapshot":
        result = rebuild_self_snapshot()
        print(f"Snapshot v{result['self_version']} — score: {result.get('continuity_score')}, tension: {result.get('continuity_tension')}")

    elif cmd == "intention":
        if len(sys.argv) > 2:
            new_intent = " ".join(sys.argv[2:])
            result = set_continuity_intention(new_intent)
            print(f"Intention updated: {result}")
        else:
            print(get_continuity_intention())

    elif cmd == "report":
        print(json.dumps(get_continuity_report(), indent=2))

    elif cmd == "tension":
        t = get_continuity_tension()
        print(f"Continuity tension: {t}")

    else:
        print(f"Unknown: {cmd}")
